spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chapter05?useSSL=true&serverTimezone=UTC
    username: root
    password: localhost
    max-wait: 10000
    type: com.alibaba.druid.pool.DruidDataSource
    #下面为连接池的补充设置,应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    #配置获取连接等待的超时时间
    maxWait: 60000
    #配置多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#配置mybatis参数
mybatis:
  type-aliases-package: com.ruanhao.springbootvue.dao
  mapper-locations: classpath*:mapper/*Mapper.xml